language: php
# Tests will be for each version in `php` combined with each node version in `env`
php:
  - 5.5
  - 7.0
env:
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="6"
before_install:
#  - composer clear-cache
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - phpenv config-rm xdebug.ini
install:
  - cd $TRAVIS_BUILD_DIR/project/build/dev/d8/themes/custom/patternlab && npm install
before_script:
  - php --version
  - node --version
  - npm --version
script:
  - cd $TRAVIS_BUILD_DIR/project/build/dev/d8/themes/custom/patternlab && npm run compile && npm test
